### ISSUE TITLE
Error: Cannot find module '../models/User'

### ISSUE THREAD

**Issue by arijitdirghangi** [effortlessdevsec/ninjasworkout#1]
┌──(root💀Hacker)-[~/bugbounty/vulnerable_application/ninjasworkout]
└─# node app.js
/root/bugbounty/vulnerable_application/ninjasworkout/images
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../models/User'
Require stack:
- /root/bugbounty/vulnerable_application/ninjasworkout/routers/index.js
- /root/bugbounty/vulnerable_application/ninjasworkout/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/bugbounty/vulnerable_application/ninjasworkout/routers/index.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/bugbounty/vulnerable_application/ninjasworkout/routers/index.js',
    '/root/bugbounty/vulnerable_application/ninjasworkout/app.js'
  ]
}

**Comment by arijitdirghangi** [comment]
i am using wsl

**Comment by effortlessdevsec** [comment]
@arijitdirghanji  hi, I added some changes and tried on local ,its working fine now . please rebuild it with new changes , let me know if issue persists.

**Comment by arijitdirghangi** [comment]
Thanks its working fine
